execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ wooden_door -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ spruce_door -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ birch_door -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ jungle_door -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ acacia_door -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ dark_oak_door -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ spruce_fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ birch_fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ jungle_fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ acacia_fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ dark_oak_fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ trapdoor -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ spruce_trapdoor -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ birch_trapdoor -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ jungle_trapdoor -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ acacia_trapdoor -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ dark_oak_trapdoor -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ crimson_door -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ warped_door -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ crimson_fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ warped_fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ crimson_fence_gate -1 tag @s add doordestroy
execute @e[family=monster,rym=-135,ry=-45] ~~~ detect ~1~~ warped_fence_gate -1 tag @s add doordestroy